---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liu.
--- DateTime: 2025/10/15 14:15
---
local key = KEYS[1]
local defaultValue = tonumber(ARGV[1])
local expireSeconds = tonumber(ARGV[2])

local value = redis.call("GET", key)
if not value then
    redis.call("SET", key, defaultValue, "EX", expireSeconds)
else
    value = redis.call("INCR", key)
    return value
end