---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liu.
--- DateTime: 2025/10/15 15:13
---
local key = KEYS[1]
local current = redis.call("GET", key)
if current == false then
    redis.call("SET", key, 1)
else
    redis.call("INCR", key)
    return tonumber(current) + 1
end