spring:
  application:
    name: blogsakura_java
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template-location: false
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  token-style: uuid
  is-log: true
