spring:
  application:
    name: blogsakura_java
  # mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      stat-view-servlet:
  #        enabled: true
  #        url-pattern: /druid/*
  #        login-username: admin
  #        login-password: 123456
  thymeleaf:
    check-template-location: false
  # 处理驼峰
  jackson:
    property-naming-strategy: SNAKE_CASE
  # redis配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
      virtual-host: /
## elastic search配置
elasticsearch:
  url: http://localhost:9200

## mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  is-read-header: true

# spring事物管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    tracer: TRACE
